from app.routes.auth import auth_bp
from app.routes.admin import admin_bp
from app.routes.hr import hr_bp
from app.routes.employee import employee_bp
from app.routes.attendance import attendance_bp
from app.routes.leave import leave_bp
from app.routes.payroll import payroll_bp
from app.routes.reports import reports_bp
from app.routes.documents import documents_bp
